#!/bin/sh
#
PL="pl"
echo "You will be invoking this instance of ploticus:"
which $PL

echo
echo "Enter an output format, one of: x11, gif, png, svg, (svgz), (jpeg), or eps...."
read MODE
if [ "$MODE" = "" ]; then
  MODE=x11
fi


which $PL 
date 

OPTS=

echo "--------- stock2..." 
$PL -$MODE $OPTS  stock2.htm 

echo "--------- kmslide..." 
$PL -$MODE $OPTS  kmslide.htm 
echo "--------- propbars1..." 
$PL -$MODE $OPTS  propbars1.htm 
echo "--------- td..." 
$PL -$MODE $OPTS  td.htm 
echo "--------- errbar5..." 
$PL -$MODE $OPTS  errbar5.htm 
echo "Note: some warnings are ok in errbar5..
" 
echo "--------- scatterplot10..." 
$PL -$MODE $OPTS  scatterplot10.htm 
echo "--------- devol..." 
$PL -$MODE $OPTS  devol.htm 
echo "--------- lineplot4..." 
$PL -$MODE $OPTS  lineplot4.htm 
echo "--------- lineplot5..." 
$PL -$MODE $OPTS  lineplot5.htm 
echo "--------- pie1..." 
$PL -$MODE $OPTS  pie1.htm 
echo "--------- bars3..." 
$PL -$MODE $OPTS  bars3.htm
echo "--------- quarters..." 
$PL -$MODE $OPTS  quarters.htm 
echo "--------- timeline2..." 
$PL -$MODE $OPTS  timeline2.htm 
echo "--------- scatterplot4..." 
$PL -$MODE $OPTS  scatterplot4.htm 
echo "--------- annot2..." 
$PL -$MODE $OPTS  annot2.htm 
echo "--------- drawcom..." 
$PL -$MODE $OPTS  drawcom.htm 
echo "--------- hitcount3..." 
$PL -$MODE $OPTS  hitcount3.htm 
echo "Note: there should be 8 'warning: time is outside of window range' msgs above..
" 
echo "--------- lineplot20..." 
$PL -$MODE $OPTS  lineplot20.htm 

echo "--------- colorgrid2... (should produce client size imagemap to file csmap.out)" 
$PL -$MODE $OPTS  colorgrid2.htm -csmap > csmap.out
head -3 csmap.out

echo "--------- heatmap3..." 
$PL -$MODE $OPTS  heatmap3.htm 
echo "--------- vector1..." 
$PL -$MODE $OPTS  vector1.htm 
echo "--------- windbarbs..." 
$PL -$MODE $OPTS  windbarbs.htm 
echo "--------- supstubs..." 
$PL -$MODE $OPTS  supstubs.htm 
echo "--------- legends232..." 
$PL -$MODE $OPTS  legends232.htm 
echo "--------- venn..." 
$PL -$MODE $OPTS  venn.htm 
echo "--------- catlines1..."
$PL -$MODE $OPTS catlines1.htm
echo "--------- tree1..."
$PL -$MODE $OPTS tree1.htm
echo "--------- dtfut..."
$PL -$MODE $OPTS dtfut.htm
echo "--------- rangesweep2_dostext..."
$PL -$MODE $OPTS rangesweep2_dostext.htm
echo "--------- sar-cpu..."
$PL -$MODE $OPTS sar-cpu.htm

echo "Finished."
