#!/bin/sh
#
DEV=$1
OUTDIR=$2
ARGS=$3
if [ "$DEV" = "" ]; then
  DEV=x11
fi

echo draw1..
pl -prefab draw cmdfile=drawcom.dcm xrange="0 40" yrange="0 40" rectangle="1 1 3 3" \
        -$DEV -o ${OUTDIR}draw1.$DEV $ARGS
