static char *ps_special_std[][2] = {
{ "AE","341" }, /* AE */
{ "PL","350" }, /* Lslash */
{ "OE","352"}, /* OE */
{ "O/","351"}, /* Oslash */
{ "ae","361"}, /* ae */
{ "be","306"}, /* breve */
{ "bu","267"}, /* bu */
{ "ct","242"}, /* cent */
{ "^","303"}, /* circumflex */
{ "dg","262"}, /* dagger */
{ "dd","263"}, /* daggerdbl */
{ "um","310"}, /* dieresis */
{ "dt","307"}, /* dotaccent */
{ "ui","365"}, /* dotlessi */
{ "em","320"}, /* emdash */
{ "en","261"}, /* endash */
{ "!!","241"}, /* exclamdown */
{ "ff","--"}, /* ff */
{ "Fi","--"}, /* ffi */
{ "Fl","--"}, /* ffl */
{ "fi","256"}, /* fi */
{ "fl","257"}, /* fl */
{ "ss","--"}, /* germandbls */
{ "ga","--"}, /* grave */
{ "d<","253"}, /* guillemotleft */
{ "d>","273"}, /* guillemotright */
{ "hy","055"}, /* hyphen */
{ "lb","--"}, /* lb */
{ "lc","--"}, /* lc */
{ "lf","--"}, /* lf */
{ "lk","--"}, /* lk */
{ "Pl","370"}, /* lslash */
{ "lt","--"}, /* lt */
{ "mc","--"}, /* macron */
{ "ob","--"}, /* ob */
{ "oe","372"}, /* oe */
{ "og","316"}, /* ogonek */
{ "o/","371"}, /* oslash */
{ "pp","266"}, /* paragraph */
{ "pm","275"}, /* perthousand */
{ "??","277"}, /* questiondown */
{ "lq","252"}, /* quotedblleft */
{ "rq","272"}, /* quotedblright */
{ "n'","--"}, /* quotesingle */
{ "rb","--"}, /* rb */
{ "rc","--"}, /* rc */
{ "rf","--"}, /* rf */
{ "ri","312"}, /* ring */
{ "rk","--"}, /* rk */
{ "rn","--"}, /* rn */
{ "rt","--"}, /* rt */
{ "ru","--"}, /* ru */
{ "sc","247"}, /* Section */
{ "sq","--"}, /* sq */
{ "ps","243"}, /* sterling */
{ "~","--"}, /* tilde */
{ "ul","--"}, /* ul */
{ "vr","--"}, /* vr */
{ "yi","245"}, /* yen */
{ "@@","-1" } /* THE END */
};
static char *ps_symbol[][2] = {
{ "*d","144"}, /* delta */
{ "*e","145"}, /* epsilon */
{ "*f","146"}, /* phi */
{ "*g","147"}, /* gamma */
{ "*y","150"}, /* eta */
{ "*i","151"}, /* iota */
{ "","152"}, /* phi1 */
{ "*k","153"}, /* kappa */
{ "*l","154"}, /* lambda */
{ "*m","155"}, /* mu */
{ "*n","156"}, /* nu */
{ "*o","157"}, /* omicron */
{ "*p","160"}, /* pi */
{ "*h","161"}, /* theta */
{ "*r","162"}, /* rho */
{ "*s","163"}, /* sigma */
{ "*t","164"}, /* tau */
{ "*u","165"}, /* upsilon */
{ "","166"}, /* omega1 */
{ "*w","167"}, /* omega */
{ "*c","170"}, /* xi */
{ "*q","171"}, /* psi */
{ "*z","172"}, /* zeta */
{ "","173"}, /* braceleft */
{ "or","174"}, /* bar */
{ "","175"}, /* braceright */
{ "ap","176"}, /* similar */
{ "","241"}, /* Upsilon1 */
{ "fm","242"}, /* minute */
{ "<=","243"}, /* lessequal */
{ "","244"}, /* fraction */
{ "if","245"}, /* infinity */
{ "$D","246"}, /* florin */
{ "","247"}, /* club */
{ "dm","250"}, /* diamond */
{ "bs","251"}, /* heart */
{ "","252"}, /* spade */
{ "<>","253"}, /* arrowboth */
{ "<-","254"}, /* arrowleft */
{ "ua","255"}, /* arrowup */
{ "->","256"}, /* arrowright */
{ "da","257"}, /* arrowdown */
{ "de","260"}, /* degree */
{ "+-","261"}, /* plusminus */
{ "sd","262"}, /* second */
{ ">=","263"}, /* greaterequal */
{ "mu","264"}, /* multiply */
{ "pt","265"}, /* proportional */
{ "pd","266"}, /* partialdiff */
{ "","267"}, /* bullet */
{ "di","270"}, /* divide */
{ "!=","271"}, /* notequal */
{ "==","272"}, /* equivalence */
{ "~=","273"}, /* approxequal */
{ "","274"}, /* ellipsis */
{ "","275"}, /* arrowvertex */
{ "","276"}, /* arrowhorizex */
{ "cr","277"}, /* carriagereturn */
{ "al","300"}, /* aleph */
{ "","301"}, /* Ifraktur */
{ "","302"}, /* Rfraktur */
{ "","303"}, /* weierstrass */
{ "ax","304"}, /* circlemultiply */
{ "a+","305"}, /* circleplus */
{ "es","306"}, /* emptyset */
{ "ca","307"}, /* intersection */
{ "cu","310"}, /* union */
{ "sp","311"}, /* propersuperset */
{ "ip","312"}, /* reflexsuperset */
{ "!s","313"}, /* notsubset */
{ "sb","314"}, /* propersubset */
{ "ib","315"}, /* reflexsubset */
{ "mo","316"}, /* element */
{ "!m","317"}, /* notelement */
{ "","320"}, /* angle */
{ "gr","321"}, /* gradient */
{ "rg","322"}, /* registerserif */
{ "co","323"}, /* copyrightserif */
{ "tm","324"}, /* trademarkserif */
{ "","325"}, /* product */
{ "sr","326"}, /* radical */
{ "m.","327"}, /* dotmath */
{ "no","330"}, /* logicalnot */
{ "an","331"}, /* logicaland */
{ "lo","332"}, /* logicalor */
{ "io","333"}, /* arrowdblboth */
{ "<:","334"}, /* arrowdblleft */
{ "lh","334"}, /* arrowdblleft */
{ "","335"}, /* arrowdblup */
{ ":>","336"}, /* arrowdblright */
{ "rh","336"}, /* arrowdblright */
{ "","337"}, /* arrowdbldown */
{ "","340"}, /* lozenge */
{ "l<","341"}, /* angleleft */
{ "","342"}, /* registersans */
{ "","343"}, /* copyrightsans */
{ "","344"}, /* trademarksans */
{ "","345"}, /* summation */
{ "","346"}, /* parenlefttp */
{ "","347"}, /* parenleftex */
{ "","350"}, /* parenleftbt */
{ "","351"}, /* bracketlefttp */
{ "","352"}, /* bracketleftex */
{ "","353"}, /* bracketleftbt */
{ "","354"}, /* bracelefttp */
{ "","355"}, /* braceleftmid */
{ "","356"}, /* braceleftbt */
{ "","357"}, /* braceex */
{ "r>","361"}, /* angleright */
{ "is","362"}, /* integral */
{ "","363"}, /* integraltp */
{ "","364"}, /* integralex */
{ "","365"}, /* integralbt */
{ "","366"}, /* parenrighttp */
{ "","367"}, /* parenrightex */
{ "","370"}, /* parenrightbt */
{ "","371"}, /* bracketrighttp */
{ "","372"}, /* bracketrightex */
{ "","373"}, /* bracketrightbt */
{ "","374"}, /* bracerighttp */
{ "","375"}, /* bracerightmid */
{ "","376"}, /* bracerightbt */
{ "","40"}, /* space */
{ "","41"}, /* exclam */
{ "fa","42"}, /* universal */
{ "","43"}, /* numbersign */
{ "te","44"}, /* existential */
{ "","45"}, /* percent */
{ "","46"}, /* ampersand */
{ "","47"}, /* suchthat */
{ "","50"}, /* parenleft */
{ "","51"}, /* parenright */
{ "**","52"}, /* asteriskmath */
{ "pl","53"}, /* plus */
{ "\\-","55"}, /* minus */
{ "","56"}, /* period */
{ "sl","57"}, /* slash */
{ "eq","75"}, /* equal */
{ "","76"}, /* greater */
{ "","77"}, /* question */
{ "","100"}, /* congruent */
{ "*A","101"}, /* Alpha */
{ "*B","102"}, /* Beta */
{ "*X","103"}, /* Chi */
{ "*D","104"}, /* Delta */
{ "*E","105"}, /* Epsilon */
{ "*F","106"}, /* Phi */
{ "*G","107"}, /* Gamma */
{ "*Y","110"}, /* Eta */
{ "*I","111"}, /* Iota */
{ "","112"}, /* theta1 */
{ "*K","113"}, /* Kappa */
{ "*L","114"}, /* Lambda */
{ "*M","115"}, /* Mu */
{ "*N","116"}, /* Nu */
{ "*O","117"}, /* Omicron */
{ "*P","120"}, /* Pi */
{ "*H","121"}, /* Theta */
{ "*R","122"}, /* Rho */
{ "*S","123"}, /* Sigma */
{ "*T","124"}, /* Tau */
{ "*U","125"}, /* Upsilon */
{ "ts","126"}, /* sigma1 */
{ "*W","127"}, /* Omega */
{ "*C","130"}, /* Xi */
{ "*Q","131"}, /* Psi */
{ "*Z","132"}, /* Zeta */
{ "","133"}, /* bracketleft */
{ "tf","134"}, /* therefore */
{ "","135"}, /* bracketright */
{ "bt","136"}, /* perpendicular */
{ "\\_","137"}, /* underscore */
{ "","140"}, /* radicalex */
{ "*a","141"}, /* alpha */
{ "*b","142"}, /* beta */
{ "*x","143"}, /* chi */
{ "@@","-1" }  /* THE END */
};
